webtalk_init -webtalk_dir C:/Users/chand/Desktop/EE214/PROJECTS/juego_project9/project_9.1/project_9.1.sim/sim_1/behav/xsim/xsim.dir/cla_adderTb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov  3 16:17:19 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7a463ec1-f4bc-4445-aeb8-81c1bcdda151" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f3190d5132c44b8391f420bf25d56a77" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1114 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7284_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4160507639 -regid "" -xml C:/Users/chand/Desktop/EE214/PROJECTS/juego_project9/project_9.1/project_9.1.sim/sim_1/behav/xsim/xsim.dir/cla_adderTb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/chand/Desktop/EE214/PROJECTS/juego_project9/project_9.1/project_9.1.sim/sim_1/behav/xsim/xsim.dir/cla_adderTb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/chand/Desktop/EE214/PROJECTS/juego_project9/project_9.1/project_9.1.sim/sim_1/behav/xsim/xsim.dir/cla_adderTb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
